-- Synthetic fixtures only. Run against an isolated database after the workspace migration.
begin;
do $$
declare dept uuid; p uuid; other_p uuid; s uuid; s2 uuid; a uuid; b uuid; c uuid; t uuid; t2 uuid; th uuid; msg uuid; oldmsg uuid; d uuid; v uuid; assignment uuid; u uuid; request uuid; recipients jsonb; impact jsonb; before_date date;
begin
 insert into departments(name) values('Regression engineering') returning id into dept;
 insert into people(full_name,role) values('Author','admin') returning id into a;
 insert into people(full_name,role) values('Reviewer','contributor') returning id into b;
 insert into people(full_name,role) values('Observer','contributor') returning id into c;
 insert into projects(name,slug,venue,status,owner_id) values('Workspace regression','workspace-test-'||a,'Test','active',b) returning id into p;
 insert into projects(name,slug,venue,status,owner_id) values('Other regression','workspace-test-'||b,'Test','active',a) returning id into other_p;
 insert into scenes(project_id,name,owner_id) values(p,'Set A',a) returning id into s;
 insert into scenes(project_id,name,owner_id) values(p,'Set B',a) returning id into s2;
 insert into tasks(project_id,scene_id,title,owner_id,start_date,due_date) values(p,s,'Regression work A',a,'2026-10-01','2026-10-05') returning id into t;
 insert into tasks(project_id,scene_id,title,owner_id,start_date,due_date) values(p,s2,'Regression work B',a,'2026-10-01','2026-10-05') returning id into t2;
 insert into project_assignments(project_id,scene_id,person_id,department_id,job_title) values(p,s,b,dept,'Engineer') returning id into assignment;
 insert into discussion_threads(project_id,scene_id,context_type,created_by) values(p,s,'scene',a) returning id into th;
 insert into comments(thread_id,author_id,body) values(th,a,'Original 👍') returning id into msg;
 insert into comments(thread_id,author_id,body,created_at) values(th,a,'Old message',clock_timestamp()-interval '2 hours') returning id into oldmsg;
 update comments set body='Corrected 🎉' where id=msg;
 assert (select count(*)=1 from comment_edit_history where comment_id=msg),'Edit history not recorded';
 begin update comments set body='Late edit' where id=oldmsg;raise exception 'FAIL: late edit accepted';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 begin update comments set created_at=clock_timestamp() where id=oldmsg;raise exception 'FAIL: send time changed';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 perform workspace_action('accept_responsibility',jsonb_build_object('id',assignment),b);
 assert (select accepted_at is not null from project_assignments where id=assignment),'Responsibility not accepted';
 update project_assignments set job_title='Lead engineer' where id=assignment;
 assert (select accepted_at is null from project_assignments where id=assignment),'Changed job kept old acceptance';
 assert (select count(*)=2 from set_recipients(s)),'Automatic recipients incorrect';
 perform workspace_action('follow',jsonb_build_object('scene_id',s),c);
 select jsonb_agg(person_id order by person_id) into recipients from set_recipients(s) where person_id<>a;
 insert into documents(project_id,scene_id,title,created_by) values(p,s,'Decision plan',a) returning id into d;
 insert into document_versions(document_id,version_number) values(d,1) returning id into v;
 begin perform workspace_action('post_update',jsonb_build_object('scene_id',s,'kind','decision','body','Test','owner_id',a,'recipients','[]'::jsonb),a);raise exception 'FAIL: stale recipient preview accepted';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 begin perform workspace_action('post_update',jsonb_build_object('scene_id',s,'task_id',t2,'kind','decision','body','Test','owner_id',a,'recipients',recipients),a);raise exception 'FAIL: cross-set work accepted';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 u=workspace_action('post_update',jsonb_build_object('scene_id',s,'kind','decision','body','Proceed with revised plan','owner_id',b,'source_comment_id',msg,'document_version_id',v,'task_id',t,'needs_ack',true,'recipients',recipients),a);
 assert (select source_snapshot='Corrected 🎉' from set_updates where id=u),'Message snapshot incorrect';
 update comments set body='Later edit' where id=msg;
 assert (select source_snapshot='Corrected 🎉' from set_updates where id=u),'Decision changed after message edit';
 assert (select count(*)=2 from set_update_recipients where update_id=u),'Recipients not saved';
 perform workspace_action('unfollow',jsonb_build_object('scene_id',s),c);
 assert (select count(*)=2 from set_update_recipients where update_id=u),'Historical recipients changed';
 perform workspace_action('acknowledge',jsonb_build_object('id',u),c);
 assert (select acknowledged_at is not null from set_update_recipients where update_id=u and person_id=c),'Acknowledgement missing';
 begin perform workspace_action('acknowledge',jsonb_build_object('id',u),a);raise exception 'FAIL: nonrecipient acknowledged';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 request=workspace_action('request_schedule',jsonb_build_object('task_id',t,'start_date','2026-10-02','finish_date','2026-10-07','reason','Design revision'),a);
 begin perform workspace_action('request_schedule',jsonb_build_object('task_id',t,'start_date','2026-10-03','finish_date','2026-10-08','reason','Duplicate'),a);raise exception 'FAIL: duplicate pending request';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 select jsonb_agg(to_jsonb(x) order by x.entity_id) into impact from preview_task_reschedule(t,'2026-10-02','2026-10-07') x;
 begin perform workspace_action('review_schedule',jsonb_build_object('id',request,'decision','accepted','impact',impact),a);raise exception 'FAIL: wrong reviewer accepted';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 begin perform workspace_action('review_schedule',jsonb_build_object('id',request,'decision','accepted','impact','[]'::jsonb),b);raise exception 'FAIL: stale impact accepted';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 assert (select due_date='2026-10-05'::date from tasks where id=t),'Failed review changed dates';
 perform workspace_action('review_schedule',jsonb_build_object('id',request,'decision','accepted','impact',impact),b);
 assert (select due_date='2026-10-07'::date from tasks where id=t),'Accepted review missed dates';
 assert (select status='accepted' from schedule_change_requests where id=request),'Request not accepted';
 begin perform workspace_action('review_schedule',jsonb_build_object('id',request,'decision','accepted','impact',impact),b);raise exception 'FAIL: duplicate decision accepted';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 request=workspace_action('request_schedule',jsonb_build_object('task_id',t,'start_date','2026-10-03','finish_date','2026-10-08','reason','Another revision'),a);
 update tasks set due_date='2026-10-09' where id=t;
 begin perform workspace_action('review_schedule',jsonb_build_object('id',request,'decision','accepted','impact',impact),b);raise exception 'FAIL: outdated request accepted';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 begin perform workspace_action('review_schedule',jsonb_build_object('id',request,'decision','declined','note',''),b);raise exception 'FAIL: empty decline accepted';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 perform workspace_action('review_schedule',jsonb_build_object('id',request,'decision','declined','note','Dates have changed'),b);
 perform workspace_action('capacity',jsonb_build_object('task_id',t,'lane','Shop A','mode','outsourced','vendor','Builder','owner_id',a,'start_date','2026-10-02','finish_date','2026-10-07'),a);
 assert (select vendor='Builder' from capacity_allocations where task_id=t),'Outsourcing not saved';
 begin perform workspace_action('capacity',jsonb_build_object('task_id',t,'project_id',other_p,'lane','Shop A','mode','in_house','owner_id',a,'start_date','2026-10-02','finish_date','2026-10-07'),a);raise exception 'FAIL: cross-production capacity accepted';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 update projects set status='closed' where id=p;
 begin perform workspace_action('follow',jsonb_build_object('scene_id',s),c);raise exception 'FAIL: archive changed';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
 begin update comments set body='Archived edit' where id=msg;raise exception 'FAIL: archive message changed';exception when others then if sqlerrm like 'FAIL:%' then raise;end if;end;
end $$;
rollback;
